### PR TITLE
Fixes broken link [Fixes #84] Adds Excel spreadsheet to getting start…

### LINKED ISSUE #75: Add Excel spreadsheet of baseline metrics to Getting started toolkit
Excel : add what they need to pull for baseline (see below)
[Agency Series Data Call.xlsx](https://github.com/usds/SME-QA-Website/files/3860904/Agency.Series.Data.Call.xlsx)

### LINKED ISSUE #84: Fix broken link
# Bug Report

This link https://smeqa.usds.gov/toolkit/phone-assessment-interviews/sme-recusal-email-template/ is broken on this page: 
https://smeqa.usds.gov/hiring-phases/phone-assessment-interviews/scheduling/

It's the SME recusal template.

### LINKED ISSUE #88: Update job analysis presentations
# Bug Report

All of the items added in https://github.com/usds/SME-QA-Website/pull/39 need to be verified against what is in the SME-QA archive repo.

* [x] URGENT: Before Monday post the correct job analysis workshop template presentations
* [x] URGENT: Before Monday update SME training on resume review with updated bias slides
  * archive/pilot-guides/Training-SME-Resume-Review-1role.pptx
  * archive/pilot-guides/Training-SME-Resume-Review-Multirole.pptx
* [x] URGENT: Before Monday post the correct phone interview training template
* [x] Verify that the other items in that pull request are the most up-to-date versions

## What happened

The Job Analysis Workshop templates that Martha posted in this issue https://github.com/usds/SME-QA/issues/446 did not make it into this pull request https://github.com/usds/SME-QA-Website/pull/39 (somehow). 

## What I expected to happen

The job analysis template ppts had no presenter notes which tipped us off that they were amiss.

### LINKED ISSUE #93: Add roadshow presentation to the website before 11/25 training
replaces https://github.com/usds/SME-QA/issues/1016

### LINKED ISSUE #94: Add job analysis required worksheet to the job analysis toolkit
Link to document: 

[Job.Analysis.Sample.for.Case.File.docx](https://github.com/usds/SME-QA-Website/files/3871023/Job.Analysis.Sample.for.Case.File.docx)

### PR DESCRIPTION
**Pull request by humancompanion-usds**
…ed [Fixes #75] Adds job analysis sample to job analysis toolkit [Fixes #94] Adds roadshow presentation to getting started [Fixes #93] Updates the job analysis presentation template pppts. [Fixes #88]

One note: The PDFs of the job analysis powerpoints were just there to ease creating the giant PDFs for OPM and the printer. They are now removed as the site doesn't link to them.

### CODE REVIEW

**Comment by humancompanion-usds** [comment]
Darn it! I meant to put Amends for #88, not fix. I'll reopen it when this request closes it. More to do there.

**Comment by wslack** [comment]
Is there a preview version of the site built somewhere I can view?

**Comment by wslack** [comment]
I could be missing something, but I don't see new PPTXs in here. It looks like the things you removed should have been replaced?

**Comment by wslack** [comment]
I can verify the fixes for #84, #94, #75, and #93.

Only one I'm not sure about is #88.

**Pull request merged**
