### PR TITLE
add note to clarify how to use searched resumes

### PR DESCRIPTION
**Pull request by wslack**
addresses https://github.com/usds/SME-QA-Website/issues/95

### CODE REVIEW

**Comment by wslack** [comment]
Why can't we? Or we could link to https://www.usajobs.gov/Help/how-to/account/profile/searchable/.

**Comment by humancompanion-usds** [comment]
Because I don't know where to find OPM's guidance on this particular issue. IF you can find it, go for it. That Help Center page is for applicants and helps them opt-in to resume mining. Thus it wouldn't help hiring managers and HR feel okay about reaching out to applicants. 

It's unfortunate that the ATP FAQ doesn't address this either (https://usajobs.github.io/ATP-Support/faq/). It really should. If we find the guidance I could make a pull request over there for them to add it as well.

**Comment by wslack** [comment]
There is slide 7 here: https://hr.nih.gov/sites/default/files/public/documents/about/events/hhs-hr-clinic/presentations/slides/pdf/6-hhs-hr-clinic-usa-staffingusajobs-supporting-talent-acquisition-hhs..pdf and slide 23 here: https://www.dcpas.osd.mil/Content/Documents/DineDemo_USAJobsUpdate.pdf

**Comment by humancompanion-usds** [comment]
Hmm. Perhaps adding text from that second deck:

"Agencies are encouraged to actively recruit talent from a variety of sources in addition to USAJOBS for competitive positions."

I was hoping we could link to where in the DEO handbook that is explicitly allowed or encouraged. That's just marketing materials from Jobs. No worries though. What we have is fine.

**Comment by wslack** [comment]
Sorry, I don't follow that comment. Do you want me to add that text to this PR?

We could also add this DEO handbook quote:
> You should engage in focused recruiting so that good prospects from a variety of sources are encouraged to apply, and you can more effectively fill your positions, preferably with highly qualified applicants who are well-matched to your jobs. (3-1)

or 

> Reaching out to qualified individuals from appropriate sources in an endeavor to achieve
a workforce from all segments of society based solely on fair and open competition and
merit which assures that all receive equal opportunity (3-3)

**Comment by humancompanion-usds** [comment]
Sorry. Let's combine them into this:

"Agencies are encouraged to actively recruit talent from a variety of sources in addition to usajobs.gov for competitive positions. You should engage in focused recruiting so that good prospects from a variety of sources are encouraged to apply, and you can more effectively fill your positions, preferably with highly qualified applicants who are well-matched to your open position. The <a href="https://agencyportal.usajobs.gov/">USAJOBS Agency Talent Portal</a> allows you to search over a million resumes so you can encourage someone to apply (Applications must be submitted by the applicant)."

**Comment by wslack** [comment]
I switched the order and removed a sentence for being redundant with the page intro, but this is now set for final review!

**Comment by humancompanion-usds** [comment]
Approved!

**Pull request merged**
