### PR TITLE
Revises the footer. [Fixes #257]

### LINKED ISSUE #257: Footer: Convert to fat footer
The footer should include the full site structure.

### PR DESCRIPTION
**Pull request by humancompanion-usds**

### CODE REVIEW

**Comment by wslack** [comment]
Screen Shot 2020-07-29 at 9 37 17 AM

**Comment by wslack** [comment]
My question is - do we want the USDS branding on this? @humancompanion-usds did you talk to @stephaniefaith about that?

**Comment by humancompanion-usds** [comment]
@wslack - We already had USDS at the bottom. That is what is on the site right now. All I did was add the logo and improve the abbreviation. We also already had the Privacy Policy link. The grey on top of grey is a visual problem so it needs something. Also, it the site does live in the usds.gov domain. We can't put the OPM logo there as well but, I see no reason why we cannot use our own. We made SME-QA, we own SME-QA, we continue to iterate on SME-QA, if we went away: No SME-QA.

**Comment by humancompanion-usds** [comment]
Screen Shot 2020-07-29 at 3 28 56 PM

The full footer.

**Pull request merged**
