### PR TITLE
Update SME background info sheet

### PR DESCRIPTION
**Pull request by amy-usds**
The original SME background info sheet document had confusing and inconsistent wording, did not make demographic data optional, and had insufficient options for gender.

### CODE REVIEW

**Comment by wslack** [comment]
@amy-usds four comments:

1. I can't edit the word doc; is that intentiional?
2. Do we care about the job analysis date?
3. Do we need a phone number?
4. Do we want a field for people to brag on their own experience and why they should be SMEs?

**Review by wslack — CHANGES_REQUESTED** [review]
I think we should make the form more editable, but dropped a few other comments

Also unclear to me if the fields in the new PDF version are editable.

**Comment by amy-usds** [comment]
> @amy-usds four comments:
> 
> 1. I can't edit the word doc; is that intentiional?
> 2. Do we care about the job analysis date?
> 3. Do we need a phone number?
> 4. Do we want a field for people to brag on their own experience and why they should be SMEs?

1. Yes, I mirrored OPM's functionality here from the original. It's not password protected, just locked. Removing the lock would be trivial, but could result in unintended edits.
2. I don't know... the original said "Panel Date" which I have no idea what that means or why it could possibly be relevant. Should we pull it? What about just the date the sheet is filled out?
3. Yes, I think a phone number is ideal as an emergency backup. I have used it at least once in the past.
4. No, it would add to the SME burden. Also, underconfident SMEs, of which we have had many, might be driven off by this field.

So in closing, I am proposing that as long as you agree we don't need a JA date, I can edit or pull that, but otherwise leave as-is. Please reply and I'll go from there.

**Comment by wslack** [comment]
1. I guess by default, I'd rather the form be editable by those using it.
2. I think "date" makes more sense - it means someone pulling it can easily do math to see how the numbers have changed in present day.
3. Ok!
4. Ok!

**Comment by amy-usds** [comment]
@wslack Changes as discussed made in my branch and committed there. Please review and marge after a review.

**Review by wslack — APPROVED** [review]

**Comment by wslack** [comment]
Still might want to make the PDF fillable but this is better! Thanks Amy!

**Pull request merged**
