### PR TITLE
Add written assessment tips

### PR DESCRIPTION
**Pull request by wslack**

### CODE REVIEW

**Comment by amy-usds** [comment]
I've reviewed and generally am happy with this commit, although a spellcheck PR will be needed after the fact as I caught a few errors there.

**Additions:**

- New first bullet: "Have you had one SME who has not worked on developing the written assessment attempt to take it in order to gauge difficulty level and time to complete?"

- Next to "Have you built out instructions for how to transmute the assessment scores, particularly if you have multiple reviewers?" I might include a placeholder for the template we'll eventually issue out of CMS Pilot 2 (Google sheet converted into .xls or some such)

- I might add an (e.g., active COVID-19 infection) to the final bullet.

**Review by amy-usds — CHANGES_REQUESTED** [review]
I've reviewed and generally am happy with this commit, although a spellcheck PR will be needed after the fact as I caught a few errors there.

**Additions:**

- New first bullet: "Have you had one SME who has not worked on developing the written assessment attempt to take it in order to gauge difficulty level and time to complete?"

- Next to "Have you built out instructions for how to transmute the assessment scores, particularly if you have multiple reviewers?" I might include a placeholder for the template we'll eventually issue out of CMS Pilot 2 (Google sheet converted into .xls or some such)

- I might add an (e.g., active COVID-19 infection) to the final bullet.

**Comment by wslack** [comment]
@stephaniefaith this is ready for a final check when you have a moment!

**Comment by wslack** [comment]
Notes:
- Move sections ab out how to create assessments under job analysis, leave only information about administrating it here.

**Review by stephaniefaith — APPROVED** [review]

**Pull request merged**
